<script setup lang="ts">
// @ts-ignore
import { Splide, SplideSlide } from '@splidejs/vue-splide'

const isOpen = defineModel('isOpen', { type: Boolean, default: false })

defineProps({
  images: Array as PropType<string[]>,
  startFromIndex: Number
})

function clickHandler (a: any) {
  const clieckedOnArrow = a.srcElement.classList.contains('splide__arrow') || a.srcElement instanceof SVGElement 
  const clieckedOnImage = a.srcElement.classList.contains('js-image')

  if(!clieckedOnArrow && !clieckedOnImage) {
    isOpen.value = false
  }
  
} 


</script>

<template>
  <div v-if="isOpen" @click="clickHandler" class=" fixed inset-0 z-50 bg-black/75 backdrop-blur h-screen">

      <Splide ref="slider"
       dir="ltr" :options="{
        lazyLoad: 'nearby',
        perPage: 1,
  
      }" aria-label="My Favorite Images" class="scale-up-center h-full flex justify-center items-center">
        <!-- @splide:moved="log" -->
        <SplideSlide v-for="(src, inx) in images" :key="inx" class="grid place-items-center ">
          <img class="js-image  object-contain transition-all duration-500 max-h-svh sm:max-w-[80vw]" :src loading="lazy">
        </SplideSlide>
      </Splide>

  </div>
</template>

<style scoped>

/* ----------------------------------------------
 * Generated by Animista on 2025-2-14 20:18:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}


.scale-up-center {
	-webkit-animation: scale-up-center 0.4s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
	        animation: scale-up-center 0.4s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
}
</style>
